# Docker Compose for Next.js deployment only
services:
  # Next.js Frontend
  nextjs:
    build:
      context: ./my-utc-perlis-next
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_STRAPI_API_URL: ${NEXT_PUBLIC_STRAPI_API_URL}
      STRAPI_API_TOKEN: ${STRAPI_API_TOKEN}
      STRAPI_HOSTNAME: ${STRAPI_HOSTNAME}
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      FROM_EMAIL: ${FROM_EMAIL}
      FROM_NAME: ${FROM_NAME}
    ports:
      - "3000:3000"
