import NavigationChild from "../../components/NavigationChild";
export const metadata = {
    title: 'Fasiliti',
    description: 'Generated by create next app',
}

export default function FasilitiLayout({ children }: { children: React.ReactNode }) {
    return (
        <>
        <NavigationChild />
           {children}
        </>
    );
}